fmarket/config/routes.rb
Fmarket::Application.routes.draw do
  get "pages/home" => 'pages#home',   :as => :home_path

  get "pages/about" => 'pages#about',  :as => :about_path

  get "pages/help" => 'pages#help',    :as => :help_path

  match "/signin",                      :to => "sessions#new",      :as => :signin
  match "/signup",                      :to => "companies#new",         :as => :signup #"users#new" 
  match "/logout",                      :to => "sessions#destroy",  :as => :logout
  match "/dashboard",                   :to => "users#dashboard",   :as => :dashboard
  match "/subdivisions",                :to => "companies#subdivisions", :as => :subdivisions
  match "/complex_price",               :to => "prices#complex_price", :as => :complex_price
  match "/get_complex_content",         :to => "prices#get_complex_content",  :as => :complec_content
  match "/complex_price/save_changes",  :to => "prices#save_changes",  :as => :save_changes
  match "/complex_price/reset_order",   :to => "prices#reset_order",  :as => :reset_order
  match "/orders_for_contractors",      :to => "orders#orders_for_contractors", :as => :orders_for_contractors 
  match "/create_orders",               :to => "orders#create_orders", :as => :create_orders
  match "/orders_from_customers",      :to => "orders#orders_from_customers", :as => :orders_from_customers 
  resources :prices do
    member do
      get 'get_content'
    end
  end

  resources :companies
  
  resources :orders do
    member do
      get 'get_content'
      get 'get_xml'
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :users do 
    member do 
      get 'blocking'
    end
  end

  root :to => 'pages#home'

end

fmarket/app/views/shared/_alert.html.haml
- flash.each do |key, value|
  = content_tag(:div, '<a href="" class="close">&times;</a>'.html_safe+value.to_s.html_safe, :class => "alert-box #{key}")

fmarket/app/views/shared/_form_alert.html.haml
- if o.errors && o.errors.full_messages.length > 0
  .alert-box
    %a.close{:href=> ""}
      &times;
    %ul
      - o.errors.full_messages.each do |msg|
        %li
          = msg

fmarket/app/views/shared/_menu.html.haml
/ .navbar.navbar-fixed-top
/   .navbar-inner
/     .container
/       %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
/         %span.icon-bar
/         %span.icon-bar
/         %span.icon-bar
/       %a.brand(href="#") Fmarket
/       .container.nav-collapse
/         %ul.nav
= nav_bar :fixed => :top, :brand => "Fmarket  " do
  - if logged_in?
    = menu_group do
      %li
        = link_to current_user.email, current_user
      - if current_user.admin?
        %li
          = link_to t(:company), companies_path
        %li
          = link_to t(:users), users_path
      - else
        %li
          = link_to t(:dashboard), dashboard_path
        %li
          = link_to t(:prices), prices_path
    = menu_group :pull => :right do 
      %li
        = link_to t(:loggout), logout_path
  - else
    = menu_group :pull => :right do 
      %li
        = link_to t(:sign_up), signup_path
      %li
        = link_to t(:sign_in), signin_path

fmarket/app/views/shared/_news.html.haml
= t('news.news')
.panel
  - for n in News.get_last(5) do
    .row
      .twelve.columns
        %p
          %small
            = l(n.start, :format => :news)
        %h3
          = link_to n.name,  n
          %br
        = n.paged.slice!(1)

fmarket/app/views/shared/_replacement.html.haml
= link_to t('replacemnt.add'), new_admin_replacement_path(:object => obj, :type => obj.class.name)
%table.twelve
  %thead
    %tr
      %th
        = t('replacemnt.name')
      %th
        = t('replacemnt.component')
      %th
        = t('actions')
      
  %tbody
    - obj.replacements.each do |o|
      %tr
        %td
          = o.content
        %td
          = link_to o.component.name, admin_component_path(o.component)
        %td
          = link_to t('edit'), edit_admin_replacement_path(o)
          = link_to t('destroy'), admin_replacement_path(o), :method => "delete", :confirm => t('confirm_destroy')

fmarket/app/views/shared/_reviews.html.haml
= t('reviews.reviews')
.panel
  - for n in Review.get_last(5) do
    .row
      .twelve.columns
        %h3
          = link_to n.name,  n.get_full_url
        %br
        = n.paged.slice!(1)

fmarket/app/views/shared/_seo.html.haml
= f.simple_fields_for :seo do |s| 
  = s.input :_destroy, :as => :boolean, :label => t('seo._destroy'), :input_html => {checked: !f.object.seo.persisted?}
  = s.input :title, :placeholder => t('seo.title')
  = s.input :keywords, :as => :string, :placeholder => t('seo.keywords')
  = s.input :description, :placeholder => t('seo.description'), :input_html => { :rows => 3 }

fmarket/app/views/shared/_side_nave.html.haml
.well.sidebar-nav
  %h3 Sidebar
  %ul.nav.nav-list
    %li.nav-header Sidebar
    - if logged_in?
      - if !current_user.company
        = link_to  t(:add_company), new_company_path(:parent => nil)
      - else
        %li
          = link_to current_user.company.name, current_user.company
        %li
          = link_to t(:add_subdivision), new_company_path(:parent => current_user.company)
        %li
          = link_to t(:list_subdivisions), subdivisions_path(:parent => current_user.company)
        - if current_user.company.is_head?
          %li
            = link_to t(:list_employee), users_path(:company => current_user.company)