fmarket/config/routes.rb
Fmarket::Application.routes.draw do
  get "pages/home" => 'pages#home',   :as => :home_path

  get "pages/about" => 'pages#about',  :as => :about_path

  get "pages/help" => 'pages#help',    :as => :help_path

  match "/signin",                      :to => "sessions#new",      :as => :signin
  match "/signup",                      :to => "companies#new",         :as => :signup #"users#new" 
  match "/logout",                      :to => "sessions#destroy",  :as => :logout
  match "/dashboard",                   :to => "users#dashboard",   :as => :dashboard
  match "/subdivisions",                :to => "companies#subdivisions", :as => :subdivisions
  match "/complex_price",               :to => "prices#complex_price", :as => :complex_price
  match "/get_complex_content",         :to => "prices#get_complex_content",  :as => :complec_content
  match "/complex_price/save_changes",  :to => "prices#save_changes",  :as => :save_changes
  match "/complex_price/reset_order",   :to => "prices#reset_order",  :as => :reset_order
  match "/orders_for_contractors",      :to => "orders#orders_for_contractors", :as => :orders_for_contractors 
  match "/create_orders",               :to => "orders#create_orders", :as => :create_orders
  match "/orders_from_customers",      :to => "orders#orders_from_customers", :as => :orders_from_customers 
  resources :prices do
    member do
      get 'get_content'
    end
  end

  resources :companies
  
  resources :orders do
    member do
      get 'get_content'
      get 'get_xml'
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :users do 
    member do 
      get 'blocking'
    end
  end

  root :to => 'pages#home'

end

fmarket/app/models/company.rb
class Company < ActiveRecord::Base
  acts_as_nested_set
  attr_accessible :buyer, :depth, :inn, :lft, :name, :parent_id, :rgt, :supplier

  validates :inn,   :presence => true, :format => {:with => /\d{10,12}/},
                       :length => {:within => 10..12}
  validates_uniqueness_of :inn
  validates :name,  :presence => true
  validates :subcode, :length => {:within => 3..3}
  has_many  :prices
  has_many  :users
  before_save :set_subdiv_code
  before_update :set_subdiv_code

  def last_subdiv
    Company.where("parent_id", self).last || self 
  end

  def is_head?
    !self.child?
  end
  

#private
  def set_subdiv_code
    return self.subcode if self.subcode
    last_code = (self.parent.last_subdiv.subcode.to_i if self.parent) || 0
    subcode = (last_code + 1).to_s
    self.subcode = ("0"*(3 - subcode.length)) + subcode
    puts "SUB CODE ===========#{subcode}"
  end

  def to_s
    self.name.to_s 
  end

end

fmarket/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]
  # GET /companies
  # GET /companies.json
  def subdivisions
    parent = params[:parent] #TODO: add check to correct data
    @companies = Company.find(parent).children
    respond_to do |format|
      format.html { render :index} # show.html.erb
      format.json { render json: @company }
    end
  end

  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    parent = (Company.find(params[:parent]) if params[:parent]) || nil
    @company = Company.new
    if parent #init subdiv
      @company.parent = parent
      @company.inn = parent.inn
      @company.buyer = parent.buyer
      @company.supplier = parent.supplier
    else
      flash[:info] = t(:step1_new_company)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.valid?#save
        # if !current_user.company
        #   current_user.company = @company
        #   current_user.save
        # end
        #@company.save
        format.html { redirect_to new_user_path(@company)}
        session[:new_company] = @company
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

fmarket/app/helpers/companies_helper.rb
module CompaniesHelper
end

fmarket/app/views/companies/_form.html.haml
= simple_form_for @company, defaults: { input_html: { class: 'form-horizontal' } } do |f|
  - if @company.errors.any?
    #error_explanation
      %h2= "Есть #{pluralize(@company.errors.count, "ошибка")}:"
      %ul
        - @company.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :inn, label: t(:inn)
  .field
    = f.input :name, label: t(:name_company)
  .field
    = f.label t(:is_supplier)
  .field
    = f.check_box :supplier
  .field
    = f.label t(:is_buyer)
  .field
    = f.check_box :buyer  #, :as => :check_boxes
  .actions
    = f.button :submit, label: t(:to_step2)

fmarket/app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

fmarket/app/views/companies/index.html.haml
%h1 Listing companies

%table
  %tr
    %th Inn
    %th Name
    %th Supplier
    %th Buyer
    %th Parent
    %th Block
    %th 
      = t(:subcode)
    %th
    %th
    %th
    
  - @companies.each do |company|
    %tr
      %td= company.inn
      %td= company.name
      %td= company.supplier
      %td= company.buyer
      %td= company.parent_id
      %td= company.block
      %td= company.subcode
      %td= link_to 'Show', company
      %td= link_to 'Edit', edit_company_path(company)
      %td= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Company', new_company_path

fmarket/app/views/companies/new.html.haml
%h1 
  = t(:new_company)

= render 'form'

= link_to 'Back', companies_path

fmarket/app/views/companies/show.html.haml
%p#notice= notice

%p
  %b Inn:
  = @company.inn
%p
  %b Name:
  = @company.name
%p
  %b Supplier:
  = @company.supplier
%p
  %b Buyer:
  = @company.buyer
%p
  %b Parent:
  = @company.parent_id


= link_to 'Edit', edit_company_path(@company)
\|
= link_to 'Back', companies_path