fmarket/config/routes.rb
Fmarket::Application.routes.draw do
  get "pages/home" => 'pages#home',   :as => :home_path

  get "pages/about" => 'pages#about',  :as => :about_path

  get "pages/help" => 'pages#help',    :as => :help_path

  match "/signin",                      :to => "sessions#new",      :as => :signin
  match "/signup",                      :to => "companies#new",         :as => :signup #"users#new" 
  match "/logout",                      :to => "sessions#destroy",  :as => :logout
  match "/dashboard",                   :to => "users#dashboard",   :as => :dashboard
  match "/subdivisions",                :to => "companies#subdivisions", :as => :subdivisions
  match "/complex_price",               :to => "prices#complex_price", :as => :complex_price
  match "/get_complex_content",         :to => "prices#get_complex_content",  :as => :complec_content
  match "/complex_price/save_changes",  :to => "prices#save_changes",  :as => :save_changes
  match "/complex_price/reset_order",   :to => "prices#reset_order",  :as => :reset_order
  match "/orders_for_contractors",      :to => "orders#orders_for_contractors", :as => :orders_for_contractors 
  match "/create_orders",               :to => "orders#create_orders", :as => :create_orders
  match "/orders_from_customers",      :to => "orders#orders_from_customers", :as => :orders_from_customers 
  resources :prices do
    member do
      get 'get_content'
    end
  end

  resources :companies
  
  resources :orders do
    member do
      get 'get_content'
      get 'get_xml'
    end
  end

  resources :sessions, :only => [:new, :create, :destroy]
  
  resources :users do 
    member do 
      get 'blocking'
    end
  end

  root :to => 'pages#home'

end

fmarket/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
 
  # attr_accessible :title, :body
  attr_accessible :email, :password, :password_confirmation, :name
  
  belongs_to :company

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  #validates_presence_of :email
  validates :company, :presence => true
  validates_uniqueness_of :email

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, :presence => true, :format => {:with => email_regex}
  #validates :company, :presence => true
  def print_name
    company_name = (self.company.name if self.company) || I18n.t(:no_company)
    "#{self.name}, #{company_name}"
  end

  def self.users_company(company)
    list_of_company = company.children
    #list_of_company << company
    User.where("company_id IN (?) OR company_id = ?", list_of_company, company)
  end

  def string_status
    return I18n.t(:block_unset) if self.block?
    return I18n.t(:block_set) unless self.block?
  end

end

fmarket/app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :requre_login
  skip_before_filter :require_login, :only => [:new, :create]
  
  def blocking
    if !current_user.admin?
      flash[:error] = t(:dont_may_blocking)
      redirect_to users_path
      return
    end
    @user = User.find(params[:id])
    if @user.toggle! :block
      #flash[:success] = t(:blocking_success)
    else
      flash[:error] = t(:blocking_error)
    end
    #redirect_to users_path
    render :text => @user.string_status
  end

  def new
    #redirect_to current_users if current_users 
    if session[:new_company]
      flash[:info] = t(:step2_new_user)
    end
    @user = User.new
  end

  def show
    if !current_user.admin?
      @user = current_user
    else
      @user = User.find(params[:id])
    end
  end

  def index
    page = params[:page] || 1
    if !current_user.admin?
      unless current_user.company.is_head? 
        redirect_to current_user
        return 
      end
      
      @users = User.users_company(current_user.company)
    else
      @users = User.page(1) #.order(:email).page page
    end
     
  end

  def create
    
    @user = User.new(params[:user])
    @user.company = session[:new_company] || nil
    if @user.save
      @user.company.save!
      auto_login(@user)
      flash[:success] = t(:sing_up_success)
      redirect_to @user
    else
      #if user's creating has failed - del company too
      #new_comp = session[:new_company]
      #new_comp.delete
      flash[:error] = t(:sign_up_error)
      render :new
    end 
  end

  def dashboard
    @user = current_user
  end

  def destroy
    if !current_user.admin?
      redirect_to users_path
    end
    User.find(params[:id]).destroy
    flash[:success] = t(:delete_success)
    redirect_to users_path
  end
end

fmarket/app/helpers/user_helper.rb
module UserHelper
end

fmarket/app/views/users/dashboard.html.haml
.row
  .small-10.push-0.columns
    %ul
      = link_to t(:add_price), new_price_path
    %ul
      = link_to t(:list_price), prices_path
    %ul
      = link_to t(:complex_price), complex_price_path
    %hr
    %ul
      = link_to t(:orders), orders_for_contractors_path
    %ul
      = link_to t(:orders_customers), orders_from_customers_path

fmarket/app/views/users/index.html.haml
%h1
%ul.pagination{:id => "ul_pagination"}
  %table.table.table.striped
    %caption
      = t(:users_list)
    - @users.each do |user|
      %tr
        %td
          = user.name
        %td
          = user.email
        /= link_to user.string_status, "#"
        %td
          = user.company.to_s
        %td
          %a{ :id => "user#{user.id}", :user_id => "#{user.id}", :class => "user_block" }
            = user.string_status
        %td
          = link_to t(:del_user), user, :method => :delete, :confirm => t(:are_you_shure), :title => (t(:delete) + " #{user.name}")

    

fmarket/app/views/users/new.html.haml
%h1= t(:sign_up)
%hr
/ %div{:class => "row"}
/ %div{:class =>"span9"}
= t(:input_data_for_signup)
/ %div{:class => "row"}
= simple_form_for @user do |f|
  - if @user.errors.any?
    %ul
      - @user.errors.full_messages.each do |message|
        %li= message

 
  /= form_tag users_path do 
  %p
    /= f.label :name, "Name:" 
    = f.input :name, label: t(:login)
  %p
    /= f.label :company, "company:" 
    = f.input :email
  %p
    /= f.label :password, t(:pass) + ":" 
    = f.input :password, label: t(:pass)
  %p
    //= f.label :password_confirmation, t(:pass_confirmation) + ":" 
    = f.input :password_confirmation , label: t(:pass_confirmation)
  
  %hr
  %p= f.submit t(:sign_up), :class => "btn"

fmarket/app/views/users/show.html.haml
%ul.vcard
  %li.fn 
    = user_path(@user)
  %li.email 
    = @user.email
  %li.location 
    = @user.company.name if @user.company